dist: xenial
language: java
jdk:
  - openjdk8
  - openjdk11
before_install:
  - rm ~/.m2/settings.xml || true
  - ulimit -c unlimited -S
after_success:
  - bash ci/after_success.sh
cache:
  directories:
    - "$HOME/.m2"
deploy:
  - provider: script
    script: bash ci/deploy-snapshot.sh
    on:
      repo: dropwizard/dropwizard-redis
      tags: false
      branch: master
      jdk: openjdk8
  - provider: script
    script: bash ci/deploy-release.sh
    on:
      repo: dropwizard/dropwizard-redis
      tags: true
      branch: release
      jdk: openjdk8
env:
  global:
    - secure: 2LV4A1jWk9v1AQ5j3MN+ecdxbUpFUZO5Iowh9viclDcsqdQVFzlU4rcXy0HDWDYXHEyb8mRvFogd4Ik4mM9oY4co40xiaBXubztOXgEWArPjGJ2PxxuPxIeWZJhWAakGA57DxOgO4PEnMM31V6POkNBEaiAuTLtRlgblaRnNVwiB/dCkg4uMWMnymMbWxhgxZiIA2TAc6iX6wrkSn/aoEYGJxpKBBawScL36C9bOKaXCeESWje3ytL64Q/XoyfMKDpVdyzDPeX7CnX/pk1GottftpoFLQEFrVtA210r2r2uXQyD6mNKXHYWmBryFOv4wTtf3VcVVd3opsb2BUr49aaTeuv8xC2et5FQgcU3q/AYGNFdifa42b4zPd/0AMQd0KiRq/QLKx1kfjEJwNDiwOlvw62F2JSbf1pdLlIg9fYsOtfqgzneIGOTOqhkmz18h+D5s3KOxaO/xRZTDtSQqr8huhNU9wqugmyGUWITPsy90Qrhrx/RxuJyjrbvw3pcwg6q1YD30eKoXTJUdJLb0s8be1wl9mfMJql6lgUDVvJskFak8hooDGZOWvY22abAaf7Eqbmy9OSYe3ufnZNAtVtdMmUAiM6XHJQM+QzPgkLZN8JzTA7Qwmtj88TAKkZ2dETsWfSZeym2G4/ePiUs0wve5IPx47UuxBUxtoUWvEHw=
    - secure: NwWf7r1chHJC8M59RlogbwkHy1pHWWMNXaPxYZgCjYFXPt3XTJG3d2D8o3xrWJgEmvr3vpbzlTTc7JiQhhicEajt7efmphdk0FM3wm8hqXRCUJ024g0H/OdUYqonLBFdRQOrOqU3eKTsyLXz+LIypLEKp3vl2E/F459g7UAB6lwOe0CsavZqvhSkwCD/KOsoS2NmNgV6TemnWHq+pmn5chVS8P2g3xaJ8YuwuoCmFgn6Q4F1+e7bu0oYKqA8zYoK6OO9exi9VgE5yDoTQiL1U2bo0ophQ7VZJtiNy7txAol9EfBh9nDr44x5rI9MZw5hgxhZl/GGdNrNbeaiiA4j2MvMsQia1H61e3Huk6ZP6kLOUIUXzRSlk6j1UjXlR2HBmC2lj/7YndqZQi1+hHiLeWTe60wI+bB8wTUAzEO1oS3pB7ZcwgfV1g3OQRN/ISenQd4TtgdDMSErvYUU68yOhtkO4h62sxR2GCII2REIatSTon/hDzEH8x1YJJ8gfIWTnnaNansUd5pzVIg9d47OnA+TBihNN6sd2maV2UNhDNjFUkS0NDnFfSNQ/PiaROoQ5oY4T+y580xRGqE5bq4ErZVsM4FemEISRi/qajh8jFi1JWrYGG16atdpDVwvlleSyIxXkTkb4XGg2TSk218djOJReWp8VO3BMyCE792IxQ4=
